version: 3
jobs:
  build:
    working_directory: /root/project
    docker:
      - image: karrlab/build:0.0.6
    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - cache-v1-{{ .Branch }}-
            - cache-v1-

      - run: pip3 install -e .
      - run: pip3 install -U -e git+https://github.com/KarrLab/Karr-Lab-build-utils.git#egg=Karr-Lab-build-utils
      - run: karr-lab-build-utils-3 install-requirements

      - save_cache:
          key: cache-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python2.7/site-packages
            - /usr/local/lib/python3.6/site-packages

      - run: |
          set +e

          pip3 install -e git+https://github.com/KarrLab/Karr-Lab-build-utils.git#egg=Karr-Lab-build-utils
          RESULT=$?
          if [ $RESULT -ne 0 ]; then
            exit $RESULT
          fi
          karr-lab-build-utils-3 run-tests tests --with-xunit --with-coverage
          RESULT3=$?

          karr-lab-build-utils make-and-archive-reports

          if [[ $RESULT3 -eq 0 ]]; then
            exit 0
          else
            exit 1
          fi

      - store_test_results:
          path: /root/project/tests/reports
      - store_artifacts:
          path: /root/project/.coverage.3.6.1
          destination: .coverage.3.6.1

      - store_artifacts:
          path: /root/project/docs/_build/html
          destination: docs
