version: 2
jobs:
  build:
    working_directory: /root/project
    docker:
      - image: karrlab/build:0.0.24
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: CommonSchema

    steps:
      # Clone repository
      - checkout

      # Load packages from cache
      - restore_cache:
          keys:
            - cache-v12-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - cache-v12-{{ .Branch }}-
            - cache-v12-

      # Python 3 installation tasks
      - run:
          name: Install pkg_utils (Python 3)
          command: pip3 install -U --process-dependency-links git+https://github.com/KarrLab/pkg_utils.git#egg=pkg_utils
      - run:
          name: Install karr_lab_build_utils (Python 3)
          command: pip3 install -U --process-dependency-links git+https://github.com/KarrLab/karr_lab_build_utils.git#egg=karr_lab_build_utils[all]
      - run:
          name: Install package (Python 3)
          command: pip3 install -U --process-dependency-links -e .[all]
      - run:
          name: Upgrade requirements (Python 3)
          command: karr_lab_build_utils3 upgrade-requirements

      # Save packages to cache
      - save_cache:
          key: cache-v12-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python3.6/site-packages

      # Restore Database
      - run:
          name: Restore Database
          command: |
            echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' | sudo tee /etc/apt/sources.list.d/pgdg.list > /dev/null
            wget --no-check-certificate -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O- | sudo -u root apt-key add -
            sudo apt-get update
            yes Y | sudo apt-get install postgresql-9.6 postgresql-client-9.6
            mkdir kinetic_datanator/data/cache
            python3 manage.py restore_db

      # Test code
      - run:
          name: Test code
          command: |
            set +e

            karr_lab_build_utils3 run-tests --with-xunit --with-coverage
            TEST_EXIT_CODE_PY3=$?

            # Calculate exit code and save to file for reading by the next step
            if [[ $TEST_EXIT_CODE_PY3 -eq 0 ]]; then
              echo "0" > TEST_EXIT_CODE
              exit 0
            else
              echo "0" > TEST_EXIT_CODE
              exit 1
            fi

      # Generate reports, archive results, and send notifications
      - run:
          name: Generate reports, archive results, and send notifications
          when: always
          command: |
            if [[ -f TEST_EXIT_CODE ]]; then
              INSTALLATION_EXIT_CODE=0
              TEST_EXIT_CODE=$(<TEST_EXIT_CODE)
            else
              INSTALLATION_EXIT_CODE=1
              TEST_EXIT_CODE=1
            fi

            karr_lab_build_utils3 do-post-test-tasks $INSTALLATION_EXIT_CODE $TEST_EXIT_CODE

      - store_test_results:
          path: /root/project/tests/reports
      - store_artifacts:
          path: /root/project/.coverage.3.6.5
          destination: .coverage.3.6.5
      - store_artifacts:
          path: /root/project/logs
          destination: logs
      - store_artifacts:
          path: /root/project/docs/_build/html
          destination: docs
